<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>../favicon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <!-- Trimmed builds break support for Windows 10 for some reason -->
    <!-- https://github.com/Tyrrrz/YoutubeDownloader/issues/496 -->
    <PublishTrimmed>false</PublishTrimmed>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <PropertyGroup>
    <MacOSBundleIdentifier>me.tyrrrz.youtubedownloader</MacOSBundleIdentifier>
    <MacOSBundleName>YTD</MacOSBundleName>
    <MacOSBundleDisplayName>YoutubeDownloader</MacOSBundleDisplayName>
  </PropertyGroup>

  <PropertyGroup>
    <EncryptionSalt>HimalayanPinkSalt</EncryptionSalt>
  </PropertyGroup>

  <ItemGroup>
    <!-- Expose this property in code -->
    <ProjectProperty Include="EncryptionSalt" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="../favicon.ico" Link="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AsyncImageLoader.Avalonia" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Controls.WebView" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Cogwheel" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Deorcify" />
    <PackageReference Include="DialogHost.Avalonia" />
    <PackageReference Include="Gress" />
    <PackageReference Include="MacBundle" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Material.Avalonia" />
    <PackageReference Include="Material.Avalonia.DataGrid" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Onova" />
    <PackageReference Include="PowerKit" />
    <PackageReference Include="ThisAssembly.Project" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../YoutubeDownloader.Core/YoutubeDownloader.Core.csproj" />
  </ItemGroup>
</Project>
