using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using YoutubeDownloader.Core.Utils;
using YoutubeExplode.Videos.ClosedCaptions;

namespace YoutubeDownloader.Core;

public partial record SubtitleDownloadOption(ClosedCaptionTrackInfo TrackInfo)
{
    public string Label => TrackInfo.IsAutoGenerated
        ? $"{TrackInfo.Language} (auto-generated)"
        : $"{TrackInfo.Language}";

    public async Task DownloadAsync(
        string filePath,
        IProgress<double>? progress = null,
        CancellationToken cancellationToken = default) =>
        await Youtube.Client.Videos.ClosedCaptions.DownloadAsync(TrackInfo, filePath, progress, cancellationToken);
}

public partial record SubtitleDownloadOption
{
    public static IReadOnlyList<SubtitleDownloadOption> GetAll(ClosedCaptionManifest manifest) => manifest.Tracks
        .Select(t => new SubtitleDownloadOption(t))
        .ToArray();
}