<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="CSharpier.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Gress" />
    <PackageReference Include="JsonExtensions" />
    <PackageReference Include="PowerKit" />
    <PackageReference Include="TagLibSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../YoutubeExplode/YoutubeExplode.csproj" />
    <ProjectReference Include="../YoutubeExplode.Converter/YoutubeExplode.Converter.csproj" />
  </ItemGroup>
</Project>
